import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
          <div className="min-h-screen w-full relative bg-white dark:bg-black">
            <div className="absolute inset-0 z-0 bg-gradient-to-br from-pink-100/20 via-transparent to-purple-100/20 dark:from-pink-900/10 dark:via-transparent dark:to-purple-900/10" />
            <div className="relative z-10">
              {/* <Navbar /> */}
              <ThemeProvider
                attribute="class"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
